# Generated by Django 4.2 on 2023-10-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("temperature", models.FloatField()),
                ("feels_like_temp", models.FloatField()),
                ("humidity", models.FloatField()),
                ("wind_speed", models.FloatField()),
                ("cloud_cover", models.FloatField()),
                ("visibility", models.FloatField()),
                ("weather_desc", models.CharField(max_length=255)),
                ("icon", models.CharField(max_length=10)),
                ("forecast_data", models.JSONField(default=None)),
            ],
            options={
                "db_table": "WeatherData",
            },
        ),
    ]
